function cities = city(N)

    prefix = { 
        'Ast', ...
        'Bal', ...
        'Beck', ...
        'Caer', ...
        'Chipping', ...
        'Shanty', ...
        'Charles', ...
        'Freedom', ...
        'Great', ...
        'Yeet' ...
    };
    suffix = {
        'ington', ...
        'ster', ...
        'gate', ...
        'ham', ...
        'cott', ...
        'stow', ...
        ' Town', ...
        ' New Haven', ...
        'worth', ...
        'field', ...
    };

    cities = strcat(datasample(prefix, N), datasample(suffix, N));
    
end