function cities = city(N)
% Function creates a N-sized list of random city names
% arguments
% N [int] Amount of cities
% returns
% cities [Nx1 array of string] list of city names

    prefix = { 
        'Ast', ...
        'Bal', ...
        'Beck', ...
        'Caer', ...
        'Chipping', ...
        'Shanty', ...
        'Charles', ...
        'Freedom', ...
        'Great', ...
        'Yeet', ...
        'Czi', ...
        'Lon', ...
        'War', ...
        'Zam' ...
    };
    suffix = {
        'ington', ...
        'ster', ...
        'gate', ...
        'ham', ...
        'cott', ...
        'stow', ...
        ' Town', ...
        ' New Haven', ...
        'worth', ...
        'field', ...
        'cago', ...
        'don', ...
        'tingmor', ...
        'shire' ...
    };

    cities = strcat(datasample(prefix, N), datasample(suffix, N));
    
end